apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-votingapp
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: resultapp-pod
    app: demo-votingapp