apiVersion: v1
kind: Pod
metadata:
  name: resultapp-pod
  labels:
    name: resultapp-pod
    app: demo-votingapp
spec:
  containers:
    - name: resultapp
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
