apiVersion: v1
kind: Pod
metadata:
  name: votingapp-pod
  labels:
    name: votingapp-pod
    app: demo-votingapp
spec:
  containers:
    - name: votingapp
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
